# Generated by Django 5.2.3 on 2025-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la empresa o persona cliente",
                        max_length=200,
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="RUT del cliente (ej: 76.123.456-7)",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        help_text="Dirección física del cliente",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Correo electrónico de contacto",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("cargo", models.CharField(max_length=100)),
                ("fecha_contratacion", models.DateField()),
            ],
        ),
    ]
