# Generated by Django 5.2.3 on 2025-07-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maquinaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Excavadora CAT 320D", max_length=100
                    ),
                ),
                ("patente", models.CharField(blank=True, max_length=10, null=True)),
                ("horometro_actual", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la obra o proyecto", max_length=200
                    ),
                ),
                ("ubicacion", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("horometro_inicial", models.PositiveIntegerField()),
                ("horometro_final", models.PositiveIntegerField()),
                (
                    "combustible_cargado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Litros de combustible",
                        max_digits=6,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.empleado",
                    ),
                ),
                (
                    "maquinaria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.maquinaria",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.proyecto",
                    ),
                ),
            ],
        ),
    ]
