# Generated by Django 5.2.3 on 2025-07-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_maquinaria_proyecto_movimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="codigo_trabajador",
            field=models.CharField(default="0000", max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_contrato",
            field=models.CharField(default="Indefinido", max_length=20),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_licencia",
            field=models.CharField(default="N/A", max_length=10),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="descripcion_trabajo_especial",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="turno",
            field=models.CharField(
                choices=[
                    ("Día", "Turno Día"),
                    ("Noche", "Turno Noche"),
                    ("Horas Extras", "Horas Extras"),
                    ("Trabajo Especial", "Trabajo Especial"),
                ],
                default="Turno Día",
                max_length=20,
            ),
        ),
    ]
