# Generated by Django 5.2.3 on 2025-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_empleado_codigo_trabajador_empleado_tipo_contrato_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maquinaria",
            name="nombre",
        ),
        migrations.AddField(
            model_name="maquinaria",
            name="codigo_eq",
            field=models.CharField(default="SIN-CODIGO", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="maquinaria",
            name="marca",
            field=models.CharField(default="SIN-MARCA", max_length=50),
        ),
        migrations.AddField(
            model_name="maquinaria",
            name="modelo",
            field=models.CharField(default="SIN-MODELO", max_length=50),
        ),
        migrations.AddField(
            model_name="maquinaria",
            name="tipo",
            field=models.CharField(
                default="SIN-TIPO",
                help_text="Ej: Excavadora, Cargador Frontal",
                max_length=50,
            ),
        ),
    ]
