# Generated by Django 5.2.3 on 2025-07-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_remove_maquinaria_nombre_maquinaria_codigo_eq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoLicencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="tipo_licencia",
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_termino_contrato",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_vencimiento_licencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Administrativo", "Administrativo"),
                    ("Jefe de Turno", "Jefe de Turno"),
                    ("Supervisor", "Supervisor"),
                    ("Operador Camión Tolva", "Operador Camión Tolva"),
                    ("Operador Maquinaria", "Operador Maquinaria"),
                    ("Operador Multiservicio", "Operador Multiservicio"),
                    ("Operador Mantenedor", "Operador Mantenedor"),
                    ("Mantenedor", "Mantenedor"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="tipo_contrato",
            field=models.CharField(
                choices=[("Indefinido", "Indefinido"), ("Plazo Fijo", "Plazo Fijo")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="turno",
            field=models.CharField(
                choices=[
                    ("Día", "Turno Día"),
                    ("Noche", "Turno Noche"),
                    ("Horas Extras", "Horas Extras"),
                    ("Trabajo Especial", "Trabajo Especial"),
                ],
                default="Día",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="licencias",
            field=models.ManyToManyField(blank=True, to="empresa.tipolicencia"),
        ),
    ]
