# Generated by Django 5.2.3 on 2025-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_tipolicencia_remove_empleado_tipo_licencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="detalle_chip_otro_equipo",
            field=models.CharField(
                blank=True,
                help_text="Especifique el código o patente del otro equipo",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="origen_combustible",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Estación Copec con Chip del Equipo",
                        "Estación Copec con Chip del Equipo",
                    ),
                    (
                        "Estación Copec con Chip de otro Equipo",
                        "Estación Copec con Chip de otro Equipo",
                    ),
                    ("Con Camión Combustible", "Con Camión Combustible"),
                    ("Carga Manual Con Bidones", "Carga Manual Con Bidones"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="combustible_cargado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Litros de combustible",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="proyecto",
            field=models.CharField(
                choices=[
                    ("Mina El Way", "Mina El Way"),
                    ("Mina Juana", "Mina Juana"),
                    ("Mina Paty", "Mina Paty"),
                    ("CBB Fábrica", "CBB Fábrica"),
                ],
                default="Mina El Way",
                max_length=50,
            ),
        ),
    ]
