# Generated by Django 5.2.3 on 2025-07-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0006_movimiento_detalle_chip_otro_equipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="nivel_final_combustible",
            field=models.CharField(
                choices=[
                    ("vacio", "Vacío"),
                    ("alarma", "Alarma Nivel bajo"),
                    ("un_cuarto", "1/4 Estanque"),
                    ("medio", "1/2 Estanque"),
                    ("tres_cuartos", "3/4 Estanque"),
                    ("full", "Estanque Full"),
                ],
                default="vacio",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="nivel_inicial_combustible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vacio", "Vacío"),
                    ("alarma", "Alarma Nivel bajo"),
                    ("un_cuarto", "1/4 Estanque"),
                    ("medio", "1/2 Estanque"),
                    ("tres_cuartos", "3/4 Estanque"),
                    ("full", "Estanque Full"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
