# Generated by Django 5.2.3 on 2025-07-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0007_movimiento_nivel_final_combustible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduccionEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Día", "Turno Día"),
                            ("Noche", "Turno Noche"),
                            ("Horas Extras", "Horas Extras"),
                            ("Trabajo Especial", "Trabajo Especial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "datos_despacho_fabrica",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "datos_remanejo_apoyo",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "datos_camion_tolva",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "datos_camion_aljibe",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "maquinaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.maquinaria",
                    ),
                ),
            ],
            options={
                "unique_together": {("maquinaria", "fecha", "turno")},
            },
        ),
    ]
