# Generated by Django 5.2.3 on 2025-07-06 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0008_produccionequipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[("Día", "Turno Día"), ("Noche", "Turno Noche")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255, unique=True)),
                (
                    "empresa",
                    models.CharField(
                        choices=[
                            ("Tirreno", "Tirreno"),
                            ("Mandante", "Empresa Mandante"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="nivel_final_combustible",
            field=models.CharField(
                choices=[
                    ("vacio", "Vacío"),
                    ("alarma", "Alarma Nivel Bajo"),
                    ("un_cuarto", "1/4 Estanque"),
                    ("medio", "1/2 Estanque"),
                    ("tres_cuartos", "3/4 Estanque"),
                    ("full", "Estanque Full"),
                ],
                default="vacio",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="nivel_inicial_combustible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vacio", "Vacío"),
                    ("alarma", "Alarma Nivel Bajo"),
                    ("un_cuarto", "1/4 Estanque"),
                    ("medio", "1/2 Estanque"),
                    ("tres_cuartos", "3/4 Estanque"),
                    ("full", "Estanque Full"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="turno",
            field=models.CharField(
                choices=[("Día", "Turno Día"), ("Noche", "Turno Noche")],
                default="Día",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="produccionequipo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="produccionequipo",
            name="informe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produccion_equipos",
                to="empresa.informediario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="produccionequipo",
            unique_together={("informe", "maquinaria")},
        ),
        migrations.AddField(
            model_name="informediario",
            name="jefe_mandante",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"empresa": "Mandante"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes_como_jefe",
                to="empresa.supervisor",
            ),
        ),
        migrations.AddField(
            model_name="informediario",
            name="lider_tirreno",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"empresa": "Tirreno"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes_como_lider",
                to="empresa.supervisor",
            ),
        ),
        migrations.RemoveField(
            model_name="produccionequipo",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="produccionequipo",
            name="turno",
        ),
        migrations.AlterUniqueTogether(
            name="informediario",
            unique_together={("fecha", "turno")},
        ),
    ]
