# Generated by Django 5.2.3 on 2025-07-06 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_informediario_supervisor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informediario",
            name="jefe_mandante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes_como_jefe",
                to="empresa.supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="informediario",
            name="lider_tirreno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes_como_lider",
                to="empresa.supervisor",
            ),
        ),
    ]
