# Generated by Django 5.2.3 on 2025-07-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0010_alter_informediario_jefe_mandante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="informediario",
            name="turno",
            field=models.CharField(
                choices=[
                    ("Día", "Turno Día"),
                    ("Noche", "Turno Noche"),
                    ("Horas Extras", "Horas Extras"),
                    ("Trabajo Especial", "Trabajo Especial"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="turno",
            field=models.CharField(
                choices=[
                    ("Día", "Turno Día"),
                    ("Noche", "Turno Noche"),
                    ("Horas Extras", "Horas Extras"),
                    ("Trabajo Especial", "Trabajo Especial"),
                ],
                default="Día",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Postura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_postura", models.PositiveIntegerField()),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("Producción", "Producción"),
                            ("Confinamiento", "Confinamiento"),
                            ("Remanejo", "Remanejo"),
                            ("Arriendo", "Arriendo"),
                            ("Despacho", "Despacho"),
                            ("Limpieza", "Limpieza"),
                            ("Apoyo Mina", "Apoyo Mina"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sector_prefijo",
                    models.CharField(help_text="Ej: TA, LA", max_length=10),
                ),
                ("sector_banco", models.CharField(help_text="Ej: 610", max_length=10)),
                ("sector_tiro", models.CharField(help_text="Ej: 23", max_length=10)),
                (
                    "destino",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posturas_destino",
                        to="empresa.lugar",
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posturas",
                        to="empresa.informediario",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.material",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posturas_origen",
                        to="empresa.lugar",
                    ),
                ),
            ],
            options={
                "ordering": ["informe", "numero_postura"],
                "unique_together": {("informe", "numero_postura")},
            },
        ),
    ]
