# Generated by Django 5.2.3 on 2025-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0011_lugar_material_alter_informediario_turno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postura",
            name="destino",
            field=models.CharField(
                choices=[
                    ("TA", "Mina Sector Tableado (TA)"),
                    ("LA", "Mina Sector Lagarto (LA)"),
                    ("LA_C", "Mina Sector Lagarto/Cedro (LA)"),
                    ("LA_E", "Mina Sector Lagarto/Camino Emergencia (LA)"),
                    ("LA_M", "Mina Sector Mastodonte (LA)"),
                    ("PCH", "Planta Chancado (PCH)"),
                    ("BA", "Buzón Alimentación (BA)"),
                    ("BF", "Buzón de Fino (BF)"),
                    ("BTN", "Botadero Norte (BTN)"),
                    ("BTS", "Botadero Sur (BTS)"),
                    ("BE", "Botadero Ecometales (BE)"),
                ],
                default="PCH",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postura",
            name="material",
            field=models.CharField(
                choices=[
                    ("Cal Alta Ley", "Cal tronada Alta Ley"),
                    ("Cal Normal", "Cal tronada Normal"),
                    ("Cal Cemento", "Cal tronada Cemento o Baja Ley"),
                    ("Fino", "Fino"),
                    ("Fino Ecometales", "Fino Ecometales"),
                    ("Fino Bitumix", "Fino Bitumix"),
                    ("Estéril", "Estéril"),
                    ("Descarte", "Materiales de Descarte"),
                    ("Cal 15-50", "Cal 15-50 mm"),
                    ("Cal 6-15", "Cal 6-15 mm"),
                    ("Cemento", "Cemento"),
                ],
                default="Estéril",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postura",
            name="origen",
            field=models.CharField(
                choices=[
                    ("TA", "Mina Sector Tableado (TA)"),
                    ("LA", "Mina Sector Lagarto (LA)"),
                    ("LA_C", "Mina Sector Lagarto/Cedro (LA)"),
                    ("LA_E", "Mina Sector Lagarto/Camino Emergencia (LA)"),
                    ("LA_M", "Mina Sector Mastodonte (LA)"),
                    ("PCH", "Planta Chancado (PCH)"),
                    ("BA", "Buzón Alimentación (BA)"),
                    ("BF", "Buzón de Fino (BF)"),
                    ("BTN", "Botadero Norte (BTN)"),
                    ("BTS", "Botadero Sur (BTS)"),
                    ("BE", "Botadero Ecometales (BE)"),
                ],
                default="TA",
                max_length=50,
            ),
        ),
    ]
