# Generated by Django 5.2.3 on 2025-07-07 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0012_alter_postura_destino_alter_postura_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postura",
            name="destino",
            field=models.CharField(
                choices=[
                    ("TA", "Mina Sector Tableado (TA)"),
                    ("LA", "Mina Sector Lagarto (LA)"),
                    ("LA_C", "Mina Sector Lagarto/Cedro (LA)"),
                    ("LA_E", "Mina Sector Lagarto/Camino Emergencia (LA)"),
                    ("LA_M", "Mina Sector Mastodonte (LA)"),
                    ("PCH", "Planta Chancado (PCH)"),
                    ("BA", "Buzón Alimentación (BA)"),
                    ("BF", "Buzón de Fino (BF)"),
                    ("BTN", "Botadero Norte (BTN)"),
                    ("BTS", "Botadero Sur (BTS)"),
                    ("BE", "Botadero Ecometales (BE)"),
                    ("CS", "Canchas de Stock (CS)"),
                    ("CBBF", "Fábrica (CBBF)"),
                ],
                default="PCH",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postura",
            name="material",
            field=models.CharField(
                choices=[
                    ("Cal Alta Ley", "Cal tronada Alta Ley"),
                    ("Cal Normal", "Cal tronada Normal"),
                    ("Cal Cemento", "Cal tronada Cemento o Baja Ley"),
                    ("Fino", "Fino"),
                    ("Fino Ecometales", "Fino Ecometales"),
                    ("Fino Bitumix", "Fino Bitumix"),
                    ("Estéril", "Estéril"),
                    ("Descarte", "Materiales de Descarte"),
                    ("Cal 15-50 AL", "Cal 15-50 mm Alta Ley"),
                    ("Cal 15-50 N", "Cal 15-50 mm Normal"),
                    ("Cal 6-15 AL", "Cal 6-15 mm Alta Ley"),
                    ("Cal 6-15 N", "Cal 6-15 mm Normal"),
                    ("Cemento", "Cemento"),
                ],
                default="Estéril",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postura",
            name="origen",
            field=models.CharField(
                choices=[
                    ("TA", "Mina Sector Tableado (TA)"),
                    ("LA", "Mina Sector Lagarto (LA)"),
                    ("LA_C", "Mina Sector Lagarto/Cedro (LA)"),
                    ("LA_E", "Mina Sector Lagarto/Camino Emergencia (LA)"),
                    ("LA_M", "Mina Sector Mastodonte (LA)"),
                    ("PCH", "Planta Chancado (PCH)"),
                    ("BA", "Buzón Alimentación (BA)"),
                    ("BF", "Buzón de Fino (BF)"),
                    ("BTN", "Botadero Norte (BTN)"),
                    ("BTS", "Botadero Sur (BTS)"),
                    ("BE", "Botadero Ecometales (BE)"),
                    ("CS", "Canchas de Stock (CS)"),
                    ("CBBF", "Fábrica (CBBF)"),
                ],
                default="TA",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes",
                        to="empresa.movimiento",
                    ),
                ),
                (
                    "postura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_realizados",
                        to="empresa.postura",
                    ),
                ),
            ],
            options={
                "unique_together": {("movimiento", "postura")},
            },
        ),
    ]
