# Generated by Django 5.2.4 on 2025-07-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_postura_destino_alter_postura_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='horometro_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
